# For God so loved the world, that He gave His only begotten Son, 
# that all who believe in Him should not perish but have everlasting life.
[package]
edition = "2018"
name = "nth_prime"
version = "2.1.0"

[dependencies]
bitvec = "0.20.1"